### ISSUE TITLE
Problema usando o mininet

### ISSUE THREAD

**Issue by nfss83** [latarc/umbu#13]
Pessoal,

Estou tentando rodar a sua ferramenta no mininet mas enfrentei um problema pois tive que criar manualmente duas pastas: "/umbucltransmissions/transmissions" no lado cliente e "/umbusvprojects/videos" no lado servidor. Está certo esse procedimento? 
Outra coisa tentei transmitir um pequeno arquivo de video de menos de 1 minuto, porém a ferramenta ficou indefinidamente "Receiving video..." e não saiu dessa mensagem. O que eu poderia ter feito de errado?

**Comment by carlosbda99** [comment]
Olá, boa tarde. A versão que você utilizou foi a do branch master? Ela está desatualizada, se você a tiver utilizado tente utilizando a versão do branch 'umbu-dev', é a mais recente.

**Comment by nfss83** [comment]
Eu tentei usar o master e dev. Ambas apresentaram problemas. Vou tentar usar a sugerida.

**Comment by nfss83** [comment]
Ao tentar executar o client no branch umbu-dev apareceu seguinte erro:

> umbu@1.1.9 start:client /root/umbucl
> node ./umbu/umbucl/index.js

⠋ Requesting authorization from the serverevents.js:165
      throw er; // Unhandled 'error' event


 Segue abaixo o log:

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start:client' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'prestart:client', 'start:client', 'poststart:client' ]
5 info lifecycle umbu@1.1.9~prestart:client: umbu@1.1.9
6 info lifecycle umbu@1.1.9~start:client: umbu@1.1.9
7 verbose lifecycle umbu@1.1.9~start:client: unsafe-perm in lifecycle true
8 verbose lifecycle umbu@1.1.9~start:client: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/umbucl/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle umbu@1.1.9~start:client: CWD: /root/umbucl
10 silly lifecycle umbu@1.1.9~start:client: Args: [ '-c', 'node ./umbu/umbucl/index.js' ]
11 silly lifecycle umbu@1.1.9~start:client: Returned: code: 1  signal: null
12 info lifecycle umbu@1.1.9~start:client: Failed to exec start:client script
13 verbose stack Error: umbu@1.1.9 start:client: `node ./umbu/umbucl/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid umbu@1.1.9
15 verbose cwd /root/umbucl
16 verbose Linux 4.4.0-104-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start:client"
18 verbose node v9.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error umbu@1.1.9 start:client: `node ./umbu/umbucl/index.js`
22 error Exit status 1
23 error Failed at the umbu@1.1.9 start:client script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Alguma ideia?

**Comment by carlosbda99** [comment]
Pode ser a versão do node instalada, devido a alguma dependência de pack do node, você poderia instalar a versão 10 e nos dar uma posição?

**Comment by carlosbda99** [comment]
Esse comando que você deu estava dentro do diretório do umbu? Acho que já vi esse erro ao executar fora do diretório do umbu. =(

**Comment by carlosbda99** [comment]
Nathan, teria como você descrever os procedimentos executados e o cenário utilizado? Irei tentar reproduzir o seu experimento e verificar o erro existente. Obrigado

**Comment by nfss83** [comment]
Carlos,

Ainda não tive tempo para testar o ambiente usando uma versão diferente do
Node. Assim que possível mantenho vocês informados.

Em 25 de junho de 2018 17:20, Carlos Henrique <notifications@github.com>
escreveu:

**Comment by nfss83** [comment]
Carlos,

Eu instalei o node versão 10 mas o problema continua. Segue abaixo o meu cenário para tentarem reproduzir o erro.
Estou usando um container com o mininet já instalado. Para isso, usei o https://github.com/iwaseyusuke/docker-mininet.
Node: v10.5.0
git version 2.7.4
branch: umbu-dev
Estou tentando instalar o umbu server e client nesse container. Esse versão do branch é possível instalar server e client na mesma máquina? Alguma sugestão para corrigir o problema?

**Comment by carlosbda99** [comment]
Olá Nathan,

Bem, especificamente o UMBU foi desenvolvido pra rodar (por enquanto) com SO's Ubuntu/Debian, não consegui verificar se o container que você está utilizando é baseado em uma dessas duas distribuições mas esse poderia ser um dos motivos causadores do erro. Em relação a poder ser instalado na mesma máquina não tem nenhum problema, você pode até instalar na mesma pasta que não deve gerar erro. Desde já, estamos tentando verificar o erro e irei reproduzir o cenário e tentar corrigir o erro.

**Comment by nfss83** [comment]
O container é baseado no ubuntu 16.04.

root@9e4583197355:~/umbucl# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Comment by nfss83** [comment]
Instalei o client e o server em pastas diferentes porém no mesmo container (ubuntu 16.04).

**Comment by nfss83** [comment]
Pessoal alguma novidade?

**Comment by carlosbda99** [comment]
Olá Nathan, 

após instalar o container e tentar  utilizar o umbu tive o mesmo problema na instalação, reparei que tive que fazer a instalação do npm separadamente a do nodejs o que não deveria ser necessário, estou estudando uma forma de corrigir esse erro que provavelmente será devido a alguma incompatibilidade na compilação com a versão do npm. Assim que estiver resolvido enviarei a solução para você. Peço desculpas pela demora na resposta pois estive enrolado com outro projeto. Em alguns dias já terei a solução, assim espero.

Desde já grato pelos feedbacks.

**Comment by nfss83** [comment]
Ok Carlos, fico no aguardo.

Em 3 de agosto de 2018 13:04, Carlos Henrique <notifications@github.com>
escreveu:

**Comment by nfss83** [comment]
Olá,

Estou enfrentando problemas em rodar o evalvid nos containers. Ele não
reconhece os binários tipo psnr, mp4trace,... Vocês passaram por algo
parecido?

2018-08-16 17:24 GMT-03:00 Carlos Henrique <notifications@github.com>:

**Comment by nfss83** [comment]
Para os binários funcionar tive que instalar o pacote   libc6-i386

Em qui, 6 de set de 2018 às 17:24, Carlos Henrique <notifications@github.com>
escreveu:
